[package]
edition = "2018"
name = "webassembly-language-server"
version = "0.0.0"
authors = ["Darin Morrison <darinmorrison@users.noreply.github.com>"]
license = "Apache-2.0 OR MIT"
readme = "README.md"
repository = "https://github.com/darinmorrison/webassembly-language-server"
description = """
A language server implementation for WebAssembly
"""

[badges]
maintenance = { status = "experimental" }

[build-dependencies]
cc = "1.0.50"

[dependencies]
failure = "0.1.7"
jsonrpc-core = "14.0.5"
sled = "0.31.0"
tokio = { version = "0.2.13", features = ["io-std", "macros"] }
tower-lsp = "0.9.1"
tree-sitter = "0.6.3"

[workspace]
members = [
]
