[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"

[workspace]
members = [
  "crates/cli",
  "crates/macros",
  "crates/parsers",
  "crates/server",
  "crates/testing",
  "fuzz",
  "xtask"
]
default-members = ["crates/cli"]
