[package]
edition = "2018"
name = "webassembly-language-server"
version = "0.0.0"
authors = ["Darin Morrison <darinmorrison@users.noreply.github.com>"]
license = "Apache-2.0 OR MIT"
readme = "README.md"
repository = "https://github.com/darinmorrison/webassembly-language-server"
description = """
A language server implementation for WebAssembly
"""

[badges]
maintenance = { status = "experimental" }

[dependencies]

[workspace]
members = [
]
