[package]
name = "xtask"
version = "0.1.0"
authors = ["Darin Morrison <darinmorrison@users.noreply.github.com>"]
edition = "2018"

[build-dependencies]
anyhow = "1.0.28"
built = { version = "0.4.0", features = ["git2"] }

[dependencies]
anyhow = "1.0.28"
clap = "2.33.0"
