[package]
name = "xtask"
version = "0.1.0"
authors = ["Darin Morrison <darinmorrison@users.noreply.github.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.28"
clap = "2.33.0"
env_logger = "0.7.1"
log = "0.4.8"
