
[package]
publish = false
edition = "2018"
name = "wasm-language-server-fuzz"
version = "0.0.0"
authors = ["Darin Morrison <darinmorrison@users.noreply.github.com>"]
license = "Apache-2.0 WITH LLVM-exception"

[package.metadata]
cargo-fuzz = true

[[bin]]
name = "lsp_textDocument-didOpen"
path = "fuzz_targets/lsp/text_document/did_open.rs"
bench = false
doc = false
test = false

[dependencies]
futures = "0.3"
libfuzzer-sys = "0.3"
serde_json = "1.0"
tokio = "0.2"
lspower = "0.1"
wasm-language-server-testing = { path = "../crates/testing" }
wasm-smith = "0.1"
wasmprinter = "0.2"

