
[package]
publish = false
edition = "2018"
name = "wasm-language-server-fuzz"
version = "0.0.0"
authors = ["Darin Morrison <darinmorrison@users.noreply.github.com>"]
license = "Apache-2.0 WITH LLVM-exception"

[package.metadata]
cargo-fuzz = true

[[bin]]
name = "lsp_textDocument-didOpen"
path = "fuzz_targets/lsp/text_document/did_open.rs"
bench = false
doc = false
test = false

[features]
default = ["runtime-tokio"]
runtime-smol = [
  "lspower/runtime-agnostic",
  "smol",
  "wasm-language-server/runtime-agnostic",
  "wasm-language-server-testing/runtime-agnostic",
]
runtime-tokio = [
  "lspower/runtime-tokio",
  "tokio",
  "wasm-language-server/runtime-tokio",
  "wasm-language-server-testing/runtime-tokio",
]

[dependencies]
futures = "0.3"
libfuzzer-sys = "0.3"
serde_json = "1.0"
lsp = { version = "0.86", package = "lsp-types" }
wasm-smith = "0.3"
wasmprinter = "0.2"

[dependencies.lspower]
git = "https://github.com/rslint/lspower"
branch = "main"
default-features = false

[dependencies.smol]
version = "1.2"
optional = true

[dependencies.tokio]
version = "1.0"
optional = true

[dependencies.wasm-language-server]
version = "0.0.0"
path = "../crates/server"
default-features = false

[dependencies.wasm-language-server-testing]
version = "0.0.0"
path = "../crates/testing"
default-features = false
