
[package]
publish = false
edition = "2018"
name = "wasm-language-server-fuzz"
version = "0.0.0"
authors = ["Darin Morrison <darinmorrison@users.noreply.github.com>"]
license = "Apache-2.0 WITH LLVM-exception"

[package.metadata]
cargo-fuzz = true

[[bin]]
name = "lsp_textDocument-didOpen"
path = "fuzz_targets/lsp/text_document/did_open.rs"
bench = false
doc = false
test = false

[features]
fuzz = [
  "futures",
  "libfuzzer-sys",
  "serde_json",
  "test",
  "tokio",
  "tower-lsp",
  "wabt",
  "wasm-smith",
]
test = ["wasm-language-server-testing/test"]

[dependencies]
futures = { version = "0.3", optional = true }
libfuzzer-sys = { version = "0.3", optional = true }
serde_json = { version = "1.0", optional = true }
tokio = { version = "0.2", optional = true }
tower-lsp = { version = "0.13", optional = true }
wabt = { version = "0.10", optional = true }
wasm-language-server-testing = { path = "../crates/testing", optional = true }
wasm-smith = { version = "0.1", optional = true }
