[package]
edition = "2018"
name = "wasm-language-server-testing"
version = "0.0.0"
authors = ["Darin Morrison <darinmorrison@users.noreply.github.com>"]
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
repository = "https://github.com/wasm-lsp/wasm-language-server"
keywords = ["lsp", "wasm"]
description = """
Tests and testing support code for the WebAssembly language server
"""

[badges]
maintenance = { status = "experimental" }

[features]
default = ["compression", "threaded"]
compression = ["wasm-language-server/compression"]
test = ["serde_json", "tower-test"]
threaded = ["wasm-language-server/threaded"]

[dependencies]
anyhow = "1.0.28"
serde_json = { version = "1.0", optional = true }
tower-lsp = "0.13.0"
tower-test = { version = "0.3.0", optional = true }
wasm-language-server = { path = "../server" }

[dev-dependencies]
futures = "0.3.4"
tokio = { version = "0.2.13", features = ["io-std", "macros", "sync", "time", "test-util"] }
tower-lsp = "0.13.0"
wasm-language-server-macros = { path = "../macros" }
wasm-language-server-shared = { path = "../shared" }
