[package]
edition = "2018"
name = "wasm-lsp-server"
version = "0.0.0"
authors = ["hvithrafn <hvithrafn@users.noreply.github.com>"]
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
repository = "https://github.com/wasm-lsp/wasm-language-server"
keywords = ["lsp", "wasm"]
description = """
A language server implementation for WebAssembly.
"""

[badges]
maintenance = { status = "experimental" }

[features]
default = ["runtime-tokio"]
goldenfiles = []
runtime-agnostic = ["async-lock", "lspower/runtime-agnostic"]
runtime-tokio = ["lspower/runtime-tokio", "tokio", "tokio/rt-multi-thread"]

[build-dependencies]
anyhow = "1.0"
built = { version = "0.4", features = ["git2"] }

[dependencies]
anyhow = "1.0"
bytes = "1.0"
clap = "2.33"
dashmap = "4.0"
env_logger = "0.8"
futures = "0.3"
log = "0.4"
lsp = { version = "0.86", package = "lsp-types" }
ropey = "1.2"
serde_json = "1.0"
thiserror = "1.0"
wasm-lsp-parsers = { path = "../parsers" }

[dependencies.async-lock]
version = "2.3"
optional = true

[dependencies.lspower]
git = "https://github.com/rslint/lspower"
branch = "main"
default-features = false

[dependencies.tokio]
version = "1.0"
features = ["io-std", "sync"]
optional = true

[dependencies.tree-sitter]
package = "tree-sitter-facade"
git = "https://github.com/hvithrafn/tree-sitter-facade"
branch = "main"

[dev-dependencies]
criterion = "0.3"
futures = "0.3"
glob = "0.3"
goldenfile = "1.0"
indoc = "1.0"
lsp = { version = "0.86", package = "lsp-types" }
lspower = { git = "https://github.com/rslint/lspower", branch = "main", default-features = false }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
wasm-lsp-macros = { path = "../macros", version = "0.0.0" }

[package.metadata.cargo-udeps.ignore]
normal = ["env_logger"]
