[package]
edition = "2018"
name = "wasm-language-server"
version = "0.0.0"
authors = ["Darin Morrison <darinmorrison@users.noreply.github.com>"]
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
repository = "https://github.com/wasm-lsp/wasm-language-server"
keywords = ["lsp", "wasm"]
description = """
A language server implementation for WebAssembly.
"""

[badges]
maintenance = { status = "experimental" }

[[bin]]
name = "wasm-language-server"
path = "src/bin/main.rs"

[features]
default = ["compression", "threaded"]
compression = ["sled/compression"]
corpus = []
goldenfiles = []
threaded = ["tokio/rt-multi-thread"]

[build-dependencies]
anyhow = "1.0"
built = { version = "0.4", features = ["git2"] }

[dependencies]
anyhow = "1.0"
blake3 = "0.3"
clap = "2.33"
dashmap = "4.0"
env_logger = "0.8"
futures = "0.3"
log = "0.4"
lsp = { version = "0.86", package = "lsp-types" }
lspower = { git = "https://github.com/rslint/lspower", branch = "tokio-1.0" }
ropey = "1.2"
serde_json = "1.0"
sled = "0.34"
thiserror = "1.0"
tokio = { version = "1.0", features = ["io-std", "macros", "sync"] }
tree-sitter = "0.17"
uuid = { version = "0.8", features = ["v4"] }
wasm-language-server-parsers = { path = "../parsers" }
wast = "30.0"
zerocopy = "0.3"

[dev-dependencies]
assert_cmd = "1.0"
criterion = "0.3"
futures = "0.3"
glob = "0.3"
goldenfile = "1.0"
indoc = "1.0"
lsp = { version = "0.86", package = "lsp-types" }
lspower = { git = "https://github.com/rslint/lspower", branch = "tokio-1.0" }
predicates = "1.0"
tokio = { version = "1.0" }
wasm-language-server-macros = { path = "../macros", version = "0.0.0" }
wasm-language-server-testing = { path = "../testing", version = "0.0.0" }

[package.metadata.cargo-udeps.ignore]
normal = ["env_logger"]
