[package]
edition = "2018"
name = "wasm-language-server"
version = "0.0.0"
authors = ["Darin Morrison <darinmorrison@users.noreply.github.com>"]
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
repository = "https://github.com/wasm-lsp/wasm-language-server"
keywords = ["lsp", "wasm"]
description = """
A language server implementation for WebAssembly.
"""

[[bin]]
name = "wasm-language-server"
path = "src/bin/main.rs"

[badges]
maintenance = { status = "experimental" }

[features]
default = ["compression", "threaded"]
compression = ["sled/compression"]
corpus = []
threaded = ["tokio/rt-threaded"]

[build-dependencies]
anyhow = "1.0.28"
built = { version = "0.4.0", features = ["git2"] }

[dependencies]
anyhow = "1.0.28"
clap = "2.33.0"
codespan-lsp = { git = "https://github.com/brendanzab/codespan" }
codespan-reporting = { git = "https://github.com/brendanzab/codespan" }
dashmap = "3.7.0"
env_logger = "0.7.1"
futures = "0.3.4"
log = "0.4.8"
serde_json = "1.0"
sled = "0.34.0"
thiserror = "1.0.14"
tokio = { version = "0.2.13", features = ["io-std", "macros", "sync", "time"] }
tower-lsp = "0.13.0"
tree-sitter = "0.16.1"
uuid = { version = "0.8.1", features = ["v4"] }
wasm-language-server-parsers = { path = "../parsers" }
wast = "24.0.0"
zerocopy = "0.3.0"

[dev-dependencies]
assert_cmd = "1.0"
futures = "0.3.4"
indoc = "1.0"
predicates = "1.0"
tokio = { version = "0.2.13", features = ["io-std", "macros", "sync", "time", "test-util"] }
tower-lsp = "0.13.0"
wasm-language-server-macros = { path = "../macros", version = "0.0.0" }
wasm-language-server-testing = { path = "../testing", version = "0.0.0" }

[package.metadata.cargo-udeps.ignore]
normal = ["env_logger"]
