name: criterion-compare
on:
  pull_request:
    branches:
      - main
jobs:
  criterion-compare:
    name: Run benchmarks and compare results
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Run cargo xtask init
        uses: actions-rs/cargo@v1
        with:
          command: xtask
          args: init --with-corpus
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - uses: boa-dev/criterion-compare-action@v2.0.0
        with:
          cwd: "subDirectory (optional)"
          token: ${{ secrets.GITHUB_TOKEN }}
