name: release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  create-release:
    name: Deploy release build for ${{ matrix.os }}
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release entry
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  deploy-release:
    name: Deploy release build for ${{ matrix.os }}
    needs: create-release
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [linux, windows, macos]
        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: wasm-language-server
            asset_name: wasm-language-server-linux
          - name: windows
            os: windows-latest
            artifact_name: wasm-language-server.exe
            asset_name: wasm-language-server-windows
          - name: macos
            os: macos-latest
            artifact_name: wasm-language-server
            asset_name: wasm-language-server-macos
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: Run cargo xtask init
        uses: actions-rs/cargo@v1
        with:
          command: xtask
          args: init --with-corpus
      - name: Run cargo xtask build
        uses: actions-rs/cargo@v1
        with:
          command: xtask
          args: build -- --release
      - name: Create release asset
        run: zip --junk-paths ${{ matrix.asset_name }} target/release/${{ matrix.artifact_name }}
      - name: Deploy release asset to GitHub
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./${{ matrix.asset_name }}.zip
          asset_name: ${{ matrix.asset_name }}.zip
          asset_content_type: application/zip
